### ISSUE TITLE
Unclear documentation about what's new parameter

### ISSUE THREAD

**Issue by davidvavra** [r0adkll/upload-google-play#3]
Hi, the documentation is not clear how to exactly generate files for what's new. It would be helpful to add full example.

Let's say I specify parameter as following: `whatsNewDirectory: whatsnew`

How should the files look like?

`whatsnew/whatsnew-en-US`

or 

`whatsnew-en-US/anything`

?

**Comment by iamriajul** [comment]
By seeing source code I can say that:
Files should look like and file has no extension: 
whatsnew/whatsnew-en-US
whatsnew/whatsnew-bn-BD

Source Code Screenshot:
![image](https://user-images.githubusercontent.com/24244379/73426356-46adbf00-435e-11ea-950b-bc8983370566.png)

**Comment by davidvavra** [comment]
@iamriajul Thanks.  But this should be documented in README.md.

**Comment by iamriajul** [comment]
whatsnew/whatsnew-en-US this format is not working! where is the maintainer? please clarify this whatsNewDirectory parameter documentation.
@r0adkll please clarify.
Thanks.

**Comment by r0adkll** [comment]
Sorry for the late replay, yes it's supposed to be in the format:
```
whatsnew-<locale>
```
where `locale` is the language of your whats new using the [BCP 47](https://tools.ietf.org/html/bcp47) format. I will update the readme to reflect this and be better documented.

You are right, it is currently broken and not reading the what's new files, let me fix that and push out a new release, thanks for the feedback.

**Comment by r0adkll** [comment]
@davidvavra @iamriajul Okay this should be resolved now and available using either `v1` or `v1.0.3`. I also updated the readme with better documentation on how this input is processed. 

Check it out and let me know if this helps.

**Comment by davidvavra** [comment]
Thanks @r0adkll. Will test with the next release of our app :) 

But the documentation is still not clear - you added just more language examples, but the confusion was if that pattern is for folders or files? And files should have no extension? It would be best to add example for concrete `whatsNewDirectory` folder - what should be the files named and in which folder they should be?

**Comment by r0adkll** [comment]
@davidvavra Okay, I will attempt to clarify further in the readme.

**Comment by r0adkll** [comment]
Okay, that should be much clearer now

**Comment by davidvavra** [comment]
@r0adkll Great! Thanks for fast responses and your work.

**Comment by iamriajul** [comment]
@r0adkll Thanks, whatsNewDirectory is working now. I have just released a version and Play Console has my What's New text.
Thanks again.
